version: '3'

networks:
 dev-net:
  name: dev-net
  driver: bridge

volumes:
  nginx_logs:
   name: nginx_logs
   driver: local

services:
  
  killgrave:
    image: friendsofgo/killgrave
    platform: linux/amd64
    container_name: app_server
    build:
      context: .
    volumes:
      - ./imposters:/app/imposters
    working_dir: /app
    command: -host 0.0.0.0
    networks:
      - dev-net
    expose:
      - 3000
  nginx:
    image: nginxdemos/hello
    container_name: nginx
    networks:
      - dev-net
    volumes:
      - nginx_logs:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hello.conf:/etc/nginx/conf.d/hello.conf
    ports:
      - 32769:80
    depends_on:
      - killgrave
  vector:
    image: timberio/vector:0.31.0-debian
    volumes:
      - ./vector.toml:/etc/vector/vector.toml
      - nginx_logs:/var/log/nginx/:ro
    networks:
      - dev-net
    ports:
      - 8686:8686
    container_name: vector
    depends_on: 
      - nginx

  elasticsearch:    
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0           # this works perfectly fine
    # platform: linux/amd64                                               
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0-amd64   
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - dev-net
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      
      # - bootstrap.system_call_filter=false # use to avoid the symptom eception. use it only on the amd64 version
    depends_on:
      - vector

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0           # this works perfectly fine

    # platform: linux/amd64                                 
    # image: docker.elastic.co/kibana/kibana:7.15.0-amd64   
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    networks:
      - dev-net
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch